# Generated by Django 3.0.6 on 2020-07-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('Id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
                ('Valor_cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_horas',
            fields=[
                ('Id_detalle_horas', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.CharField(max_length=50)),
                ('Cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=50)),
                ('Documento', models.CharField(max_length=50)),
                ('Tipo_documento', models.CharField(max_length=50)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
                ('Id_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('Id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('Anual', models.DateField()),
                ('Mes', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_vinculacion',
            fields=[
                ('Id_tipo_vinculacion', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion_vinculacion', models.CharField(blank=True, choices=[('Vinculado', 'Vinculado'), ('Desvinculado', 'Desvinculado')], default='Vinculado', max_length=50, null=True)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_horas',
            fields=[
                ('Id_reporte_horas', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_horas', models.CharField(max_length=50)),
                ('Id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Empleado')),
                ('Id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Parafiscales',
            fields=[
                ('Id_parafiscales', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Valor_parafiscales', models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4')], default='3', max_length=50, null=True)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
                ('Id_tipo_vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Tipo_vinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('Id_nomina', models.AutoField(primary_key=True, serialize=False)),
                ('Valor_pagar', models.CharField(max_length=50)),
                ('Subtotal', models.CharField(max_length=50)),
                ('Pago', models.CharField(max_length=50)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
                ('Id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Empleado')),
                ('Id_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Horas_extras',
            fields=[
                ('Id_horas_extras', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Valor_hora_extra', models.CharField(max_length=50)),
                ('Estado', models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50, null=True)),
                ('Id_detalle_horas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Detalle_horas')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='Id_tipo_vinculacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Tipo_vinculacion'),
        ),
        migrations.CreateModel(
            name='Detalle_parafiscales',
            fields=[
                ('Id_detalle_parafiscales', models.AutoField(primary_key=True, serialize=False)),
                ('Total_parafiscales', models.CharField(max_length=50)),
                ('Id_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Nomina')),
                ('Id_parafiscales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Parafiscales')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_horas',
            name='Id_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrar_nomina.Nomina'),
        ),
    ]
